### ISSUE TITLE
spm 配置里能否增加 buildCommand 参数执行额外的命令和插件

### ISSUE THREAD

**Issue by xuhuan** [spmjs/spm-build#62]
如题，比如下面的情况
```
spm build & gulp & ...
```
目前没看到spm-build 有挂载额外插件的地方，那能否spm配置里增加
```
buildCommand : 'gulp & ...'
```
在执行完 spm build  后继续执行 buildCommand  对应的命令，这样子就不用每次都手动输入一开始的命令。上面的可以是spm build 执行完不管成功与否都继续执行下面的命令。
碰到需要依次在前面命令执行成功的前提下执行下一个的情况可以用数组形式，如下：
```
buildCommand : ['gulp',...]
```

或者如果有其他附加插件的方式也行，可以执行额外的spm-build 没有提供的功能。

**Comment by sorrycc** [comment]
最新的 spm-build 支持 scripts 了，应该可以解决这个问题。
https://github.com/spmjs/spm-build/blob/master/test/fixtures/scripts/package.json
